<a href="https://colab.research.google.com/github/Kishan1082/Deep-Learning/blob/main/CSE_360_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANN Model

Employee Retention dataset

In [ ]:
#import the libraries

import numpy as np
import pandas as pd

df = pd.read_csv("/content/HR_comma_sep - HR_comma_sep.csv")

In [ ]:
df

satisfaction_level  last_evaluation  ...    sales  salary
0                    0.38             0.53  ...    sales     low
1                    0.80             0.86  ...    sales  medium
2                    0.11             0.88  ...    sales  medium
3                    0.72             0.87  ...    sales     low
4                    0.37             0.52  ...    sales     low
...                   ...              ...  ...      ...     ...
14994                0.40             0.57  ...  support     low
14995                0.37             0.48  ...  support     low
14996                0.37             0.53  ...  support     low
14997                0.11             0.96  ...  support     low
14998                0.37             0.52  ...  support     low

[14999 rows x 10 columns]

In [ ]:
df1 =["sales","salary"]
df_final = pd.get_dummies(df, columns=df1, drop_first=True)

In [ ]:
df_final

satisfaction_level  last_evaluation  ...  salary_low  salary_medium
0                    0.38             0.53  ...           1              0
1                    0.80             0.86  ...           0              1
2                    0.11             0.88  ...           0              1
3                    0.72             0.87  ...           1              0
4                    0.37             0.52  ...           1              0
...                   ...              ...  ...         ...            ...
14994                0.40             0.57  ...           1              0
14995                0.37             0.48  ...           1              0
14996                0.37             0.53  ...           1              0
14997                0.11             0.96  ...           1              0
14998                0.37             0.52  ...           1              0

[14999 rows x 19 columns]

In [ ]:
#spliting x and y variable

X = df_final.drop(['left'], axis =1).values
y = df_final['left'].values

In [ ]:
X

array([[0.38, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 0.  , 0.  , 1.  ],
       [0.11, 0.88, 7.  , ..., 0.  , 0.  , 1.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [ ]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(9, kernel_initializer="uniform", activation = 'relu', input_dim = 18))
model.add(Dense(5, kernel_initializer="uniform", activation ='relu'))
model.add(Dense(1, kernel_initializer= "uniform", activation ="sigmoid"))
model.compile(optimizer='adam', loss="binary_crossentropy", metrics =["accuracy"])

In [ ]:
model.fit(X_train, y_train, epochs=150)

Epoch 1/150
329/329 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7616
Epoch 2/150
329/329 [==============================] - 1s 4ms/step - loss: 0.3753 - accuracy: 0.7631
Epoch 3/150
329/329 [==============================] - 1s 4ms/step - loss: 0.3330 - accuracy: 0.8140
Epoch 4/150
329/329 [==============================] - 1s 4ms/step - loss: 0.3053 - accuracy: 0.8834
Epoch 5/150
329/329 [==============================] - 1s 3ms/step - loss: 0.2845 - accuracy: 0.9094
Epoch 6/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2696 - accuracy: 0.9156
Epoch 7/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2578 - accuracy: 0.9215
Epoch 8/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2476 - accuracy: 0.9253
Epoch 9/150
329/329 [==============================] - 2s 5ms/step - loss: 0.2384 - accuracy: 0.9303
Epoch 10/150
329/329 [==============================] - 1s 4ms/step - loss: 0.2306 - accura

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([[3.4000903e-05],
       [4.2078376e-02],
       [9.4962120e-03],
       ...,
       [3.4567714e-03],
       [1.2172222e-02],
       [8.1912905e-01]], dtype=float32)

In [ ]:
y_pred = y_pred.round()
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9508888888888889

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3312,  104],
       [ 117,  967]])

Churn Model dataset

In [ ]:
df = pd.read_csv("/content/Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [ ]:
df_drop =df.iloc[:, 0:3]

In [ ]:
df_final=df.drop(df_drop, axis=1)
df_final

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [ ]:
df_final.shape

(10000, 11)

In [ ]:
#One hot encoding of categorical data
df1 =['Geography','Gender']
df_final = pd.get_dummies(df_final,columns=df1,drop_first=True)
df_final.head()

CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...                  0                0            0
1          608   41       1  ...                  0                1            0
2          502   42       8  ...                  0                0            0
3          699   39       1  ...                  0                0            0
4          850   43       2  ...                  0                1            0

[5 rows x 12 columns]

In [ ]:
# Split the independent and dependent variables
X = df_final.drop(['Exited'],axis=1)
y = df_final['Exited']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [ ]:
# Standardising the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = Sequential()

# Input Layer
ann.add(Dense(12, input_dim=11,kernel_initializer='uniform',activation='relu'))

# Hidden layer
ann.add(Dense(8,activation='relu'))

# Output layer
ann.add(Dense(1,activation='sigmoid'))

In [ ]:
# compile the model
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Fit the model
res = ann.fit(X_train,y_train,batch_size=32,epochs= 200)

Epoch 1/200
219/219 [==============================] - 1s 3ms/step - loss: 0.5585 - accuracy: 0.7780
Epoch 2/200
219/219 [==============================] - 1s 3ms/step - loss: 0.4133 - accuracy: 0.8214
Epoch 3/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3932 - accuracy: 0.8299
Epoch 4/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3833 - accuracy: 0.8314
Epoch 5/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3754 - accuracy: 0.8351
Epoch 6/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3680 - accuracy: 0.8343
Epoch 7/200
219/219 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8400
Epoch 8/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3548 - accuracy: 0.8501
Epoch 9/200
219/219 [==============================] - 1s 2ms/step - loss: 0.3499 - accuracy: 0.8593
Epoch 10/200
219/219 [==============================] - 1s 3ms/step - loss: 0.3452 - accura

In [ ]:
y_pred = np.round(ann.predict(X_test)).astype(int)

In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[2290,   88],
       [ 343,  279]])

In [ ]:
round(accuracy_score(y_test,y_pred),4)*100

85.63

# CNN model

In [ ]:
from keras.datasets import mnist
from keras.layers import Dropout, Conv2D, MaxPool2D, Flatten
from keras.utils import np_utils

In [ ]:
#to calculate accuracy
from sklearn.metrics import accuracy_score

# loading the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
# building the input vector from the 28x28 pixels
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28,1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [ ]:
#normalizing the data to help with the training
X_train /= 255
X_test /= 255

In [ ]:
# One hot encoding using keras numpy related utilities
n_classes = 10
print("before encoding:",y_train.shape)
y_train = np_utils.to_categorical(y_train,n_classes)
y_test = np_utils.to_categorical(y_test,n_classes)
print("After encoding:",y_train.shape)

before encoding: (60000,)
After encoding: (60000, 10)


In [ ]:
# building a linear stack of layers with the sequential model
model = Sequential()
#convultional layer
model.add(Conv2D(32, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape =(28, 28, 1)))
model.add(MaxPool2D(pool_size=(1,1)))
#flatten output of conv
model.add(Flatten())
#hidden layer
model.add(Dense(100, activation='relu'))
#output layer
model.add(Dense(10, activation ='softmax'))

#compiling the sequential model
model.compile(loss = 'categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [ ]:
#training the model for 10 epochs
model.fit(X_train, y_train, batch_size=120, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
500/500 [==============================] - 72s 143ms/step - loss: 0.1762 - accuracy: 0.9493 - val_loss: 0.0728 - val_accuracy: 0.9774
Epoch 2/10
500/500 [==============================] - 62s 125ms/step - loss: 0.0551 - accuracy: 0.9836 - val_loss: 0.0563 - val_accuracy: 0.9817
Epoch 3/10
500/500 [==============================] - 46s 93ms/step - loss: 0.0330 - accuracy: 0.9901 - val_loss: 0.0556 - val_accuracy: 0.9820
Epoch 4/10
500/500 [==============================] - 47s 94ms/step - loss: 0.0201 - accuracy: 0.9941 - val_loss: 0.0524 - val_accuracy: 0.9833
Epoch 5/10
500/500 [==============================] - 46s 93ms/step - loss: 0.0129 - accuracy: 0.9961 - val_loss: 0.0534 - val_accuracy: 0.9830
Epoch 6/10
500/500 [==============================] - 47s 93ms/step - loss: 0.0086 - accuracy: 0.9975 - val_loss: 0.0554 - val_accuracy: 0.9826
Epoch 7/10
500/500 [==============================] - 47s 94ms/step - loss: 0.0069 - accuracy: 0.9981 - val_loss: 0.0570 - val_accurac

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 26, 26, 32)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 21632)             0         
                                                                 
 dense_6 (Dense)             (None, 100)               2163300   
                                                                 
 dense_7 (Dense)             (None, 10)                1010      
                                                                 
Total params: 2,164,630
Trainable params: 2,164,630
Non-trainable params: 0
____________________________________________