In [1]:

#import the libraries

import numpy as np
import pandas as pd

df = pd.read_csv("/content/HR_comma_sep - HR_comma_sep.csv")

In [3]:
df

satisfaction_level  last_evaluation  ...    sales  salary
0                    0.38             0.53  ...    sales     low
1                    0.80             0.86  ...    sales  medium
2                    0.11             0.88  ...    sales  medium
3                    0.72             0.87  ...    sales     low
4                    0.37             0.52  ...    sales     low
...                   ...              ...  ...      ...     ...
14994                0.40             0.57  ...  support     low
14995                0.37             0.48  ...  support     low
14996                0.37             0.53  ...  support     low
14997                0.11             0.96  ...  support     low
14998                0.37             0.52  ...  support     low

[14999 rows x 10 columns]

In [7]:
df1 =["sales","salary"]
df_final = pd.get_dummies(df, columns=df1, drop_first=True)

In [8]:
df_final

satisfaction_level  last_evaluation  ...  salary_low  salary_medium
0                    0.38             0.53  ...           1              0
1                    0.80             0.86  ...           0              1
2                    0.11             0.88  ...           0              1
3                    0.72             0.87  ...           1              0
4                    0.37             0.52  ...           1              0
...                   ...              ...  ...         ...            ...
14994                0.40             0.57  ...           1              0
14995                0.37             0.48  ...           1              0
14996                0.37             0.53  ...           1              0
14997                0.11             0.96  ...           1              0
14998                0.37             0.52  ...           1              0

[14999 rows x 19 columns]

In [9]:
#spliting x and y variable

X = df_final.drop(['left'], axis =1).values
y = df_final['left'].values

In [10]:
X

array([[0.38, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.8 , 0.86, 5.  , ..., 0.  , 0.  , 1.  ],
       [0.11, 0.88, 7.  , ..., 0.  , 0.  , 1.  ],
       ...,
       [0.37, 0.53, 2.  , ..., 0.  , 1.  , 0.  ],
       [0.11, 0.96, 6.  , ..., 0.  , 1.  , 0.  ],
       [0.37, 0.52, 2.  , ..., 0.  , 1.  , 0.  ]])

In [11]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 1)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [23]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(9, kernel_initializer="uniform", activation = 'relu', input_dim = 18))
model.add(Dense(5, kernel_initializer="uniform", activation ='relu'))
model.add(Dense(1, kernel_initializer= "uniform", activation ="sigmoid"))
model.compile(optimizer='adam', loss="binary_crossentropy", metrics =["accuracy"])

In [24]:
model.fit(X_train, y_train, epochs=150)

Epoch 1/150
329/329 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7626
Epoch 2/150
329/329 [==============================] - 0s 1ms/step - loss: 0.3767 - accuracy: 0.7771
Epoch 3/150
329/329 [==============================] - 0s 1ms/step - loss: 0.3358 - accuracy: 0.8332
Epoch 4/150
329/329 [==============================] - 0s 1ms/step - loss: 0.2996 - accuracy: 0.8741
Epoch 5/150
329/329 [==============================] - 0s 1ms/step - loss: 0.2645 - accuracy: 0.9032
Epoch 6/150
329/329 [==============================] - 0s 1ms/step - loss: 0.2415 - accuracy: 0.9148
Epoch 7/150
329/329 [==============================] - 0s 1ms/step - loss: 0.2267 - accuracy: 0.9218
Epoch 8/150
329/329 [==============================] - 0s 1ms/step - loss: 0.2147 - accuracy: 0.9271
Epoch 9/150
329/329 [==============================] - 0s 1ms/step - loss: 0.2039 - accuracy: 0.9307
Epoch 10/150
329/329 [==============================] - 0s 1ms/step - loss: 0.1930 - accura

In [25]:
y_pred = model.predict(X_test)
y_pred

array([[0.0124377 ],
       [0.05068347],
       [0.00644466],
       ...,
       [0.00411254],
       [0.00535563],
       [0.9559036 ]], dtype=float32)

In [27]:
y_pred = y_pred.round()
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9604444444444444

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[3371,   45],
       [ 133,  951]])

### Churn Model

In [31]:
df = pd.read_csv("/content/Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]